### ISSUE TITLE
adding model parameter

### ISSUE THREAD

**Issue by matteoredaelli** [sohlex/botkit-rasa#3]
The /parse get request can accept a "model" parameter

$ curl 'localhost:5000/parse?q=hello&model=hotels'
$ curl -XPOST localhost:5000/parse -d '{"q":"I am looking for Chinese food", "model": "restaurants"}'

as you can see at https://github.com/RasaHQ/rasa_nlu/blob/master/docs/http.rst

is it possible to manage it in this package?

thanks
matteo

**Comment by sohlex** [comment]
Hi,
with version [1.0.6 of the package](https://www.npmjs.com/package/botkit-rasa) is now is possible to specify a `rasa_model` when instantiating the Rasa middleware.

I updated the example bot accordingly: https://github.com/sohlex/botkit-rasa/blob/master/example/bot.js#L67 . 
Obviously instead of `undefined` the user should put a string, like `'restaurants'`.

I think this covers your use case, all the queries that the bot is going to receive will be processed using the specified model. Is this the enhancement that you asked for?

Best,
Alessio

**Comment by sohlex** [comment]
Requirements are met, closing issue.
